-- Delivery Planner schema for Supabase/PostgreSQL.
-- Run this file in Supabase Dashboard -> SQL Editor.
-- This schema is used by the Supabase-backed server repository.

create table if not exists public.users (
  id text primary key,
  email text not null unique,
  password_hash text not null,
  password_salt text not null,
  role text not null check (role in ('admin', 'merchant', 'driver', 'customer')),
  name text not null,
  ref_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.merchants (
  id text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.stores (
  id text primary key,
  merchant_id text not null references public.merchants(id),
  name text not null,
  pickup_lat double precision not null,
  pickup_lng double precision not null,
  created_at timestamptz not null default now()
);

create table if not exists public.customers (
  id text primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.drivers (
  id text primary key,
  name text not null,
  vehicle_type text not null check (vehicle_type in ('bike', 'car', 'van', 'truck')),
  capacity integer not null,
  max_package_size text not null check (max_package_size in ('small', 'medium', 'large')),
  created_at timestamptz not null default now()
);

create table if not exists public.driver_status (
  driver_id text primary key references public.drivers(id),
  status text not null check (status in ('available', 'on_route', 'break', 'offline')),
  current_order_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.driver_locations (
  id bigint generated by default as identity primary key,
  driver_id text not null references public.drivers(id),
  lat double precision not null,
  lng double precision not null,
  recorded_at timestamptz not null default now()
);
create index if not exists idx_driver_locations_driver
  on public.driver_locations(driver_id, id desc);

create table if not exists public.admin_invites (
  admin_id text primary key references public.users(id) on delete cascade,
  invite_code text not null unique,
  created_at timestamptz not null default now()
);
create table if not exists public.merchant_admins (
  merchant_id text primary key references public.merchants(id) on delete cascade,
  admin_id text not null references public.users(id) on delete cascade,
  created_at timestamptz not null default now()
);
create table if not exists public.driver_stores (
  driver_id text not null references public.drivers(id) on delete cascade,
  store_id text not null references public.stores(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (driver_id, store_id)
);
create table if not exists public.join_requests (
  id text primary key,
  requester_user_id text not null references public.users(id) on delete cascade,
  kind text not null check (kind in ('merchant_admin','driver_store')),
  target_admin_id text references public.users(id) on delete cascade,
  target_store_id text references public.stores(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','rejected')),
  created_at timestamptz not null default now(),
  decided_at timestamptz
);
create index if not exists idx_join_requests_target
  on public.join_requests(target_admin_id, target_store_id, status);

create table if not exists public.orders (
  id text primary key,
  merchant_id text not null references public.merchants(id),
  store_id text not null references public.stores(id),
  customer_id text not null references public.customers(id),
  pickup_lat double precision not null,
  pickup_lng double precision not null,
  delivery_lat double precision not null,
  delivery_lng double precision not null,
  status text not null default 'created' check (status in (
    'created', 'ready', 'validated', 'dispatching', 'assigned',
    'picked_up', 'delivering', 'delivered', 'cancelled', 'failed'
  )),
  priority text not null default 'standard' check (priority in ('standard', 'express')),
  deadline_ts timestamptz not null,
  package_size text not null check (package_size in ('small', 'medium', 'large')),
  volume integer not null default 1,
  note text,
  created_at timestamptz not null default now(),
  ready_at timestamptz
);
create index if not exists idx_orders_merchant on public.orders(merchant_id);
create index if not exists idx_orders_customer on public.orders(customer_id);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id text not null references public.orders(id),
  name text not null,
  qty integer not null default 1
);

create table if not exists public.deliveries (
  id text primary key,
  order_id text not null unique references public.orders(id),
  driver_id text references public.drivers(id),
  status text not null default 'pending' check (status in (
    'pending', 'assigned', 'en_route_pickup', 'picked_up',
    'en_route_drop', 'delivered', 'cancelled', 'failed'
  )),
  assigned_at timestamptz,
  pickup_at timestamptz,
  delivered_at timestamptz,
  estimated_delivery_minutes double precision,
  actual_delivery_minutes double precision,
  eta_ts timestamptz,
  route_id text,
  created_at timestamptz not null default now()
);

create table if not exists public.routes (
  id text primary key,
  delivery_id text not null references public.deliveries(id),
  driver_id text not null references public.drivers(id),
  origin_lat double precision not null,
  origin_lng double precision not null,
  legs_json jsonb not null,
  path_json jsonb not null,
  distance_km double precision not null,
  eta_minutes double precision not null,
  traffic_penalty_minutes double precision not null default 0,
  active integer not null default 1 check (active in (0, 1)),
  created_at timestamptz not null default now()
);
create index if not exists idx_routes_delivery on public.routes(delivery_id, active);

create table if not exists public.assignments (
  id text primary key,
  order_id text not null references public.orders(id),
  driver_id text not null references public.drivers(id),
  status text not null check (status in ('proposed', 'active', 'cancelled', 'superseded', 'rejected')),
  score double precision not null,
  reasoning_json jsonb not null,
  idempotency_key text unique,
  created_at timestamptz not null default now()
);
create index if not exists idx_assignments_order on public.assignments(order_id, status);
-- Prevent concurrent dispatch requests from leaving multiple live assignments
-- for the same order. The service-role backend still performs the workflow;
-- this index is the final database-level safety net.
create unique index if not exists uq_assignments_live_order
  on public.assignments(order_id)
  where status in ('proposed', 'active');

create table if not exists public.road_segments (
  id text primary key,
  ax integer not null,
  ay integer not null,
  bx integer not null,
  by integer not null,
  status text not null default 'clear' check (status in ('clear', 'moderate', 'heavy', 'closed')),
  delay_minutes double precision not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.traffic_conditions (
  id text primary key,
  area text not null,
  status text not null check (status in ('clear', 'moderate', 'heavy')),
  delay_minutes double precision not null default 0,
  source text,
  updated_at timestamptz not null default now()
);

create table if not exists public.agent_events (
  id bigint generated by default as identity primary key,
  ts timestamptz not null default now(),
  cycle_id text,
  agent text not null,
  event_type text not null,
  order_id text references public.orders(id),
  delivery_id text references public.deliveries(id),
  driver_id text references public.drivers(id),
  message text not null,
  data_json jsonb
);
create index if not exists idx_agent_events_order on public.agent_events(order_id, id desc);

-- The backend should access these tables with the server-only Supabase
-- service-role key. RLS prevents accidental access using the browser anon key.
alter table public.users enable row level security;
alter table public.merchants enable row level security;
alter table public.stores enable row level security;
alter table public.customers enable row level security;
alter table public.drivers enable row level security;
alter table public.driver_status enable row level security;
alter table public.driver_locations enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.deliveries enable row level security;
alter table public.routes enable row level security;
alter table public.assignments enable row level security;
alter table public.road_segments enable row level security;
alter table public.traffic_conditions enable row level security;
alter table public.agent_events enable row level security;
