import { AppState, CustomerOrder, DriverCondition, RoadSegment, Route, TrafficCondition } from './types';
import { loadConfig } from './storage';

const headers=(key:string)=>({apikey:key,Authorization:`Bearer ${key}`,'Content-Type':'application/json',Prefer:'return=minimal'});
async function getRows<T>(table:string):Promise<T[]> { const config=loadConfig(); if(!config.url||!config.anonKey) throw new Error('Supabase credentials are missing'); const response=await fetch(`${config.url}/rest/v1/${table}?select=*`,{headers:headers(config.anonKey)}); if(!response.ok) throw new Error(`Could not load ${table}`); return response.json() as Promise<T[]>; }

export async function loadCloudState():Promise<AppState> {
  const [traffic,orders,drivers,roads]=await Promise.all([
    getRows<Record<string,unknown>>('traffic_conditions'),getRows<Record<string,unknown>>('customer_orders'),getRows<Record<string,unknown>>('driver_conditions'),getRows<Record<string,unknown>>('road_segments')
  ]);
  return {
    traffic:traffic.map(row=>({id:String(row.id),area:String(row.area),status:row.status as TrafficCondition['status'],delay:Number(row.delay_minutes||0),source:String(row.source||''),updated:String(row.observed_at||'')})),
    orders:orders.map(row=>({id:String(row.id),customer:String(row.customer_name),location:String(row.location),zone:String(row.zone||''),items:String(row.items),delivery:String(row.delivery_window),priority:row.priority as CustomerOrder['priority'],volume:Number(row.volume_units||1),status:String(row.status||'Ready'),gridX:row.grid_x==null?undefined:Number(row.grid_x),gridY:row.grid_y==null?undefined:Number(row.grid_y)})),
    drivers:drivers.map(row=>({id:String(row.id),name:String(row.driver_name),availability:row.availability as DriverCondition['availability'],load:Number(row.current_load||0),position:String(row.current_position),maxLoad:Number(row.maximum_load||0),vehicle:String(row.vehicle||'')})),
    roads:roads.map(row=>({id:String(row.id),startX:Number(row.start_x),startY:Number(row.start_y),endX:Number(row.end_x),endY:Number(row.end_y),status:row.status as RoadSegment['status'],delay:Number(row.delay_minutes||0),source:String(row.source||''),orientation:(row.orientation || (Number(row.start_y)===Number(row.end_y)?'horizontal':'vertical')) as RoadSegment['orientation'],roadGroup:String(row.road_group || (Number(row.start_y)===Number(row.end_y)?`H-ROW-${row.start_y}`:`V-COL-${row.start_x}`))}))
  };
}
export async function syncInput(kind:'traffic'|'orders'|'drivers',item:Record<string,unknown>):Promise<void>{const c=loadConfig();if(!c.url||!c.anonKey)return;const table={traffic:'traffic_conditions',orders:'customer_orders',drivers:'driver_conditions'}[kind];const body=kind==='traffic'?{area:item.area,status:item.status,delay_minutes:item.delay,source:item.source}:kind==='orders'?{customer_name:item.customer,location:item.location,zone:item.zone,items:item.items,delivery_window:item.delivery,priority:item.priority,volume_units:item.volume,status:item.status,grid_x:item.gridX,grid_y:item.gridY}:{driver_name:item.name,availability:item.availability,current_load:item.load,current_position:item.position,maximum_load:item.maxLoad,vehicle:item.vehicle};const response=await fetch(`${c.url}/rest/v1/${table}`,{method:'POST',headers:{...headers(c.anonKey),Prefer:'return=representation'},body:JSON.stringify(body)});if(!response.ok)throw new Error(`Could not save ${table}`);}
export async function syncRoad(road:RoadSegment):Promise<void>{const c=loadConfig();if(!c.url||!c.anonKey)return;const response=await fetch(`${c.url}/rest/v1/road_segments?id=eq.${encodeURIComponent(road.id)}`,{method:'PATCH',headers:{...headers(c.anonKey),Prefer:'return=minimal'},body:JSON.stringify({status:road.status,delay_minutes:road.delay,source:road.source,orientation:road.orientation,road_group:road.roadGroup,observed_at:new Date().toISOString()})});if(!response.ok)throw new Error('Could not save road status');}
export async function syncRoutes(routes:Route[],graph:unknown):Promise<void>{const c=loadConfig();if(!c.url||!c.anonKey)return;const response=await fetch(`${c.url}/rest/v1/planned_routes`,{method:'POST',headers:headers(c.anonKey),body:JSON.stringify(routes.map(r=>({route_code:r.id,distance_km:r.distance,eta_minutes:r.eta,capacity_percent:r.fill,graph_snapshot:graph})))});if(!response.ok)throw new Error('Could not save routes');}
