import { AppState, Graph, Route, DriverCondition, CustomerOrder, RoadSegment } from './types';
import { coordinateForOrder } from './map';

const colors=['#f26249','#159c99','#5277d7','#f1c75b'];
const DEPOT={x:10,y:10};

function segmentTime(segment:RoadSegment|undefined):number { if(!segment)return 2; if(segment.status==='Closed')return 9999; const multiplier=segment.status==='Heavy'?3:segment.status==='Moderate'?2:1; return 2*multiplier+segment.delay; }
function roadBetween(a:{x:number;y:number},b:{x:number;y:number},roads:RoadSegment[]):RoadSegment|undefined { return roads.find(r=>(r.startX===a.x&&r.startY===a.y&&r.endX===b.x&&r.endY===b.y)||(r.startX===b.x&&r.startY===b.y&&r.endX===a.x&&r.endY===a.y)); }
function travelCost(a:{x:number;y:number},b:{x:number;y:number},roads:RoadSegment[]):{minutes:number;segments:number} { let current={...a},minutes=0,segments=0; const step=(axis:'x'|'y')=>{while(current[axis]!==b[axis]){const next={...current};next[axis]+=current[axis]<b[axis]?1:-1;minutes+=segmentTime(roadBetween(current,next,roads));segments++;current=next;}};step('x');step('y');return {minutes,segments}; }
function optimizeStops(orders:CustomerOrder[],roads:RoadSegment[]):CustomerOrder[] { const remaining=[...orders],result:CustomerOrder[]=[];let position=DEPOT;while(remaining.length){let bestIndex=0,bestScore=Infinity;remaining.forEach((order,index)=>{const score=travelCost(position,coordinateForOrder(order,index),roads).minutes-(order.priority==='Express'?100:0);if(score<bestScore){bestScore=score;bestIndex=index;}});const next=remaining.splice(bestIndex,1)[0];result.push(next);position=coordinateForOrder(next,result.length-1);}return result; }
export function planRoutes(state:AppState):Route[] { const drivers=state.drivers.filter(d=>d.availability!=='Break').sort((a,b)=>(a.availability==='Available'?0:1)-(b.availability==='Available'?0:1));const orders=[...state.orders].filter(o=>o.status!=='Delivered').sort((a,b)=>(a.priority==='Express'?0:1)-(b.priority==='Express'?0:1));const groups:Record<string,{driver:DriverCondition;orders:CustomerOrder[]}>={};const loads=Object.fromEntries(drivers.map(d=>[d.id,d.load]));orders.forEach(order=>{const driver=drivers.find(d=>loads[d.id]+order.volume<=d.maxLoad)||drivers.reduce((best,d)=>!best||loads[d.id]<loads[best.id]?d:best,null as DriverCondition|null)||({id:'UNASSIGNED',name:'Unassigned',availability:'Available',load:0,maxLoad:1,position:'—',vehicle:'—'} as DriverCondition);loads[driver.id]=(loads[driver.id]||0)+order.volume;(groups[driver.id] ||= {driver,orders:[]}).orders.push(order);});return Object.values(groups).map((group,index)=>{const optimized=optimizeStops(group.orders,state.roads);let total=0,segments=0;let position=DEPOT;optimized.forEach((order,i)=>{const next=coordinateForOrder(order,i);const leg=travelCost(position,next,state.roads);total+=leg.minutes;segments+=leg.segments;position=next;});const back=travelCost(position,DEPOT,state.roads);total+=back.minutes;segments+=back.segments;return {id:`RT-${String(index+1).padStart(2,'0')}`,driver:group.driver,orders:optimized,distance:Number((segments*.5).toFixed(1)),eta:total,stops:optimized.length,fill:Math.round(loads[group.driver.id]/Math.max(group.driver.maxLoad,1)*100),color:colors[index%colors.length]};}); }
export function buildGraph(state:AppState,routes:Route[]):Graph { const nodes=[{id:'DEPOT',type:'depot',coordinate:DEPOT},...state.drivers.map(d=>({id:d.id,type:'driver',availability:d.availability,capacity:d.maxLoad})),...state.orders.map((o,index)=>({id:o.id,type:'customer',zone:o.zone,volume:o.volume,deliveryWindow:o.delivery,coordinate:coordinateForOrder(o,index)})),...state.traffic.map(t=>({id:t.id,type:'traffic',area:t.area,delayMinutes:t.delay})),...state.roads.map(r=>({id:r.id,type:'road',status:r.status,delayMinutes:r.delay,start:{x:r.startX,y:r.startY},end:{x:r.endX,y:r.endY}}))];const edges=routes.flatMap(r=>r.orders.map(o=>({from:r.driver.id,to:o.id,weight:r.eta/Math.max(r.stops,1),blocked:false}))).concat(state.roads.map(r=>({from:r.id,to:'ROAD_NETWORK',weight:segmentTime(r),blocked:r.status==='Closed'})));return {nodes,edges}; }
