import { AppState, Route } from './types';
import { loadState, saveConfig, loadConfig } from './storage';
import { planRoutes, buildGraph } from './graph';
import { syncRoutes } from './cloud';

const state:AppState=loadState(); let selected=0; const root=document.querySelector<HTMLDivElement>('#view-root')!;
const esc=(v:unknown):string=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]!));
const routes=():Route[]=>planRoutes(state); const tag=(v:string,c='')=>`<span class="tag ${c}">${esc(v)}</span>`;
const head=(k:string,t:string,d:string,a='')=>`<div class="page-heading"><div><p class="eyebrow">${k}</p><h1>${t}</h1><p>${d}</p></div><div class="actions">${a}</div></div>`;
const notice=(m:string)=>{const e=document.querySelector<HTMLDivElement>('#toast')!;e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200);};
function map(rs:Route[]):string { const p=['65,245 172,178 280,222 401,130 538,181 678,91','65,245 145,307 264,285 398,340 531,295 678,352','65,245 205,230 326,171 452,210 575,151 678,91','65,245 177,116 300,97 407,145 545,90 678,91']; return `<div class="map-preview"><svg class="route-svg" viewBox="0 0 740 430" preserveAspectRatio="none"><path class="route-line faint" d="M20 350 L130 250 L180 240 L250 135 L345 160 L430 80 L520 140 L610 60 L730 120"/>${rs.map((r,i)=>`<polyline class="route-line ${i===selected?'active':''}" style="stroke:${r.color}" points="${p[i%4]}"/>`).join('')}<circle class="route-node driver" cx="65" cy="245" r="8"/><circle class="route-node customer" cx="172" cy="178" r="6"/><circle class="route-node customer" cx="280" cy="222" r="6"/><circle class="route-node customer" cx="401" cy="130" r="6"/><text x="45" y="274">DEPOT</text><text x="615" y="65">NORTH</text></svg><div class="map-legend"><span>Planned route</span><span>Street network</span><span>Stop</span></div></div>`; }
function layout():void {const page=location.hash.slice(1)||'overview';document.querySelectorAll<HTMLElement>('[data-route]').forEach(a=>a.classList.toggle('active',a.dataset.route===page));document.querySelector('#page-kicker')!.textContent=page;root.innerHTML=page==='overview'?overview():page==='routes'?routePage():tablePage(page);bind();}
function overview():string {const rs=routes(),g=buildGraph(state,rs);return head('Tuesday · 08:42','Good morning, Alex.','Your network is ready for the first delivery wave.','<button class="btn" data-action="refresh">↻ Refresh data</button><button class="btn primary" data-action="generate">Generate routes →</button>')+`<div class="stats-grid"><div class="stat-card"><div class="stat-head"><span>Active routes</span><span class="stat-icon">⌁</span></div><div class="stat-number">${rs.length}</div><div class="stat-trend">↑ 2 from yesterday</div></div><div class="stat-card"><div class="stat-head"><span>Open orders</span><span class="stat-icon">□</span></div><div class="stat-number">${state.orders.length}</div><div class="stat-trend">↑ 8.4% this morning</div></div><div class="stat-card"><div class="stat-head"><span>Fleet ready</span><span class="stat-icon">♧</span></div><div class="stat-number">${state.drivers.filter(d=>d.availability==='Available').length} / ${state.drivers.length}</div><div class="stat-trend neutral">${state.drivers.filter(d=>d.availability==='On route').length} currently on route</div></div><div class="stat-card"><div class="stat-head"><span>Traffic watch</span><span class="stat-icon">≋</span></div><div class="stat-number">${state.traffic.filter(t=>t.status==='Heavy').length}</div><div class="stat-trend warn">Needs attention</div></div></div><div class="grid-2-1"><section class="panel"><div class="panel-title"><div><h2>Network at a glance</h2><p>${g.nodes.length} graph nodes · ${g.edges.length} connections</p></div></div>${map(rs)}</section><section class="panel"><div class="panel-title"><div><h2>Today’s routes</h2><p>${rs.length} routes planned</p></div></div><div class="route-summary">${rs.map((r,i)=>`<div class="route-item ${i===selected?'active':''}" data-route-index="${i}"><i class="route-color" style="background:${r.color}"></i><div><strong>${r.id} · ${esc(r.driver.name)}</strong><span>${r.stops} stops · ${r.distance.toFixed(1)} km · ${r.eta} min</span></div><b>${r.fill}%<small>capacity</small></b></div>`).join('')}</div></section></div>`;}
function routePage():string {const rs=routes();return head('Workspace / planning','Route board','Select a route to highlight its path.','<button class="btn primary" data-action="generate">Recalculate routes →</button>')+`<div class="route-board"><section class="panel route-list-panel"><div class="route-list-head"><h2>${rs.length} routes planned</h2><p>Capacity and traffic-aware assignments.</p></div><div class="route-list">${rs.map((r,i)=>`<div class="route-card ${i===selected?'active':''}" data-route-index="${i}"><div class="route-card-top"><i style="background:${r.color}"></i><strong>${r.id}</strong><span>${r.fill}% full</span></div><p>${esc(r.driver.name)} · ${esc(r.driver.vehicle)}</p><div class="route-meta"><span><b>${r.stops}</b> stops</span><span><b>${r.distance.toFixed(1)}</b> km</span><span><b>${r.eta}</b> min</span></div></div>`).join('')}</div></section><section class="panel route-map-panel">${map(rs)}</section></div>`;}
function tablePage(page:string):string {const title=page==='traffic'?'Traffic conditions':page==='orders'?'Customer needs':page==='drivers'?'Driver conditions':'Settings';if(page==='settings'){const c=loadConfig();return head('Workspace / configuration','Settings','Connect Supabase for cloud persistence.')+`<section class="form-card"><h2>Supabase connection</h2><p>Use the public anon key only.</p><form id="settings-form"><div class="field"><label>Project URL</label><input name="url" value="${esc(c.url||'')}" placeholder="https://your-project.supabase.co"/></div><div class="field" style="margin-top:13px"><label>Publishable / anon key</label><input name="anonKey" type="password" value="${esc(c.anonKey||'')}"/></div><div class="form-footer"><button class="btn primary">Save connection</button></div></form></section>`;}const rows=page==='traffic'?state.traffic.map(t=>`<tr><td class="mono">${t.id}</td><td><strong>${esc(t.area)}</strong></td><td>${tag(t.status,t.status==='Heavy'?'red':t.status==='Moderate'?'orange':'green')}</td><td>+${t.delay} min</td><td>${esc(t.source)}</td></tr>`):page==='orders'?state.orders.map(o=>`<tr><td class="mono">${o.id}</td><td><strong>${esc(o.customer)}</strong><br>${esc(o.location)}</td><td>${esc(o.items)}</td><td class="mono">${esc(o.delivery)}</td><td>${tag(o.priority,o.priority==='Express'?'red':'blue')}</td></tr>`):state.drivers.map(d=>`<tr><td><strong>${esc(d.name)}</strong><br><span class="mono">${d.id}</span></td><td>${tag(d.availability,d.availability==='Available'?'green':d.availability==='On route'?'blue':'orange')}</td><td class="mono">${d.load} / ${d.maxLoad}</td><td>${esc(d.position)}</td><td class="mono">${d.maxLoad} units</td></tr>`);const th=page==='traffic'?'<th>Signal</th><th>Area</th><th>Condition</th><th>Delay</th><th>Source</th>':page==='orders'?'<th>Order</th><th>Customer / location</th><th>Items</th><th>Delivery window</th><th>Priority</th>':'<th>Driver</th><th>Availability</th><th>Current load</th><th>Current position</th><th>Maximum load</th>';return head('Inputs',''+title,'Review and manage imported operational data.',`<button class="btn primary" data-action="refresh">Refresh data</button>`)+`<section class="panel"><div class="panel-title"><div><h2>${title}</h2><p>Live workspace data</p></div></div><div class="table-wrap"><table class="data-table"><thead><tr>${th}</tr></thead><tbody>${rows.join('')}</tbody></table></div></section>`;}
function bind():void {document.querySelectorAll<HTMLElement>('[data-route-index]').forEach(e=>e.onclick=()=>{selected=Number(e.dataset.routeIndex);layout();});document.querySelectorAll<HTMLElement>('[data-action]').forEach(e=>e.onclick=()=>{if(e.dataset.action==='generate'){const rs=routes();syncRoutes(rs,buildGraph(state,rs));location.hash='routes';}else{layout();notice('Route graph refreshed.');}});document.querySelector<HTMLFormElement>('#settings-form')?.addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget);saveConfig(String(f.get('url')||''),String(f.get('anonKey')||''));notice('Supabase connection saved.');layout();});}
window.addEventListener('hashchange',layout); layout();
